const categoryImages={
health:"https://images.unsplash.com/photo-1556228578-8c89e6adf883?auto=format&fit=crop&w=700&q=85",
clothes:"https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=700&q=85",
electronics:"https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=700&q=85",
shoes:"https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=700&q=85",
watches:"https://images.unsplash.com/photo-1523170335258-f5ed11844a49?auto=format&fit=crop&w=700&q=85",
computers:"https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=700&q=85",
phones:"https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=700&q=85"
};
const uiImages={store:"https://images.unsplash.com/photo-1472851294608-062f824d29cc?auto=format&fit=crop&w=120&q=80",discounts:"https://images.unsplash.com/photo-1607082349566-187342175e2f?auto=format&fit=crop&w=120&q=80",services:"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=120&q=80",invoice:"https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=120&q=80",bonus:"wheel-icon.svg",shipping:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Afghanistan%20provinces%20blue.png",home:"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=120&q=80"};
const categories=[
["فروشگاه بهداشتی","health"],["فروشگاه لباس","clothes"],["لوازم الکترونی","electronics"],["کفش","shoes"],["ساعت های برند","watches"],["کامپیوتر ها","computers"],["گوشی ها","phones"]];
const provinces=["بدخشان","بادغیس","بغلان","بلخ","بامیان","دایکندی","فراه","فاریاب","غور","غزنی","هلمند","هرات","جوزجان","کابل","کندهار","کاپیسا","خوست","کنر","کندز","لغمان","لوگر","ننگرهار","نیمروز","نورستان","پکتیا","پکتیکا","پنجشیر","پروان","سمنگان","سرپل","تخار","ارزگان","وردک","زابل"];
let products=JSON.parse(localStorage.getItem("azimi_products")||"null")||[
{id:1,number:1,cat:"health",name:"نمونه محصول بهداشتی",desc:"محصول نمونه برای شروع فروشگاه",price:850,sale:650,img:""},
{id:2,number:2,cat:"phones",name:"گوشی نمونه AZIMI",desc:"این محصول را از پنل مدیریت تغییر بده",price:12000,sale:null,img:""},
{id:3,number:3,cat:"watches",name:"ساعت برند",desc:"نمونه ساعت برای فروشگاه",price:3200,sale:2600,img:""}
];
let cart=JSON.parse(localStorage.getItem("azimi_cart")||"[]");let bonusWeek=localStorage.getItem("azimi_bonus_week")||"";
let lang=localStorage.getItem("azimi_lang")||"fa";
let currentPage="home";
let orderNo=Number(localStorage.getItem("azimi_order_no")||0);
const WA="93786548116";
const app=document.getElementById("app");

const T={
fa:{home:"خانه",store:"فروشگاه",discounts:"لوازم تخفیفی",services:"ساخت و طراحی سایت و اپلیکیشن",invoice:"صورت حساب",bonus:"بونوس هفتگی",shipping:"ارسالی به ۳۴ ولایت",admin:"پنل مدیریت",welcome:"خوش آمدید به AZIMI SHOP",back:"← صفحه اصلی",view:"مشاهده محصولات ←",add:"افزودن به سبد",moved:"✓ انتقال یافت به صورت حساب",empty:"هنوز محصولی در این بخش ثبت نشده است.",cartEmpty:"سبد خرید شما خالی است.",total:"جمع کل",orderInfo:"اطلاعات سفارش",name:"نام و نام خانوادگی",wa:"شماره WhatsApp فعال",phone:"شماره تماس",province:"ولایت را انتخاب کنید",address:"آدرس دقیق، ناحیه، کوچه و محل تحویل",order:"ثبت سفارش و آماده‌سازی WhatsApp",homeTitle:"خرید متفاوت،|تجربه متفاوت.",homeDesc:"فروشگاه اختصاصی AZIMI SHOP برای محصولات منتخب، تخفیف‌های ویژه، خدمات دیجیتال و ارسال به تمام ۳۴ ولایت افغانستان.",enter:"ورود به فروشگاه ↗",catHint:"یک دسته را انتخاب کن؛ محصولات فقط توسط مدیریت اضافه می‌شوند.",discountEmpty:"هنوز محصول تخفیفی ثبت نشده است.",servicesTitle:"خدمات دیجیتال AZIMI",servicesDesc:"ساخت و طراحی انواع سایت‌ها، فروشگاه‌های اینترنتی، اپلیکیشن‌های موبایل و نرم‌افزارهای کامپیوتر.",web:"طراحی سایت",webDesc:"سایت شرکتی، فروشگاهی و اختصاصی",mobile:"اپلیکیشن موبایل",mobileDesc:"Android / iOS",desktop:"نرم‌افزار کامپیوتر",desktopDesc:"سیستم‌های اختصاصی",weekly:"هر مشتری فقط یک بار در هر هفته شانس دارد.",spin:"چرخاندن چرخ",shippingDesc:"ارسال سفارش به تمام ۳۴ ولایت افغانستان انجام می‌شود.",register:"ثبت محصول جدید",pname:"نام محصول",desc:"توضیحات",price:"قیمت",sale:"قیمت تخفیفی (اختیاری)",stock:"موجودی",photo:"انتخاب عکس محصول از گوشی یا کامپیوتر",category:"دسته‌بندی",registerBtn:"ثبت محصول",prizeManage:"مدیریت جوایز بونوس",prizeName:"نام جایزه",addPrize:"افزودن جایزه",delete:"حذف",registered:"محصولات ثبت‌شده",noProduct:"هنوز محصولی ثبت نشده است.",statsCat:"دسته فروشگاه",statsProv:"ولایت تحت پوشش",statsChance:"شانس هفتگی",statsOnline:"ویترین آنلاین",successCart:"محصول به سبد خرید اضافه شد 🛒",successOrder:"سفارش آماده ارسال به WhatsApp شد",fill:"تمام معلومات ارسال را تکمیل کن",emptyCart:"سبد خرید خالی است",registeredProduct:"محصول با شماره #",thisWeek:"این هفته قبلاً چرخ را چرخانده‌ای.",prize:"🎉 جایزه شما:",purpose:"Premium digital market",imgTip:"عکس انتخاب‌شده"},
en:{home:"Home",store:"Store",discounts:"Discounted Items",services:"Website & App Design",invoice:"Invoice",bonus:"Weekly Bonus",shipping:"Shipping to 34 Provinces",admin:"Admin Panel",welcome:"Welcome to AZIMI SHOP",back:"← Home",view:"View products →",add:"Add to cart",moved:"✓ Moved to invoice",empty:"No product has been added here yet.",cartEmpty:"Your cart is empty.",total:"Total",orderInfo:"Order information",name:"Full name",wa:"Active WhatsApp number",phone:"Phone number",province:"Select province",address:"Exact address, district, street and delivery location",order:"Place order & prepare WhatsApp",homeTitle:"Shop differently,|experience differently.",homeDesc:"AZIMI SHOP for selected products, special discounts, digital services and delivery to all 34 provinces of Afghanistan.",enter:"Enter Store ↗",catHint:"Choose a category; products are added by management only.",discountEmpty:"No discounted product has been added yet.",servicesTitle:"AZIMI Digital Services",servicesDesc:"Website, online store, mobile app and computer software design and development.",web:"Website Design",webDesc:"Business, store and custom websites",mobile:"Mobile App",mobileDesc:"Android / iOS",desktop:"Computer Software",desktopDesc:"Custom systems",weekly:"Each customer gets one chance per week.",spin:"Spin the wheel",shippingDesc:"Orders can be shipped to all 34 provinces of Afghanistan.",register:"Register New Product",pname:"Product name",desc:"Description",price:"Price",sale:"Discount price (optional)",stock:"Stock",photo:"Choose product photo from phone or computer",category:"Category",registerBtn:"Register product",prizeManage:"Weekly Bonus Management",prizeName:"Prize name",addPrize:"Add prize",delete:"Delete",registered:"Registered products",noProduct:"No products registered yet.",statsCat:"Store categories",statsProv:"Provinces covered",statsChance:"Weekly chance",statsOnline:"Online showcase",successCart:"Product added to cart 🛒",successOrder:"Order is ready for WhatsApp",fill:"Complete all delivery information",emptyCart:"Your cart is empty",registeredProduct:"Product #",thisWeek:"You already used this week's spin.",prize:"🎉 Your prize:",purpose:"Premium digital market",imgTip:"Selected photo"},
ps:{home:"کور",store:"هټۍ",discounts:"تخفیفي توکي",services:"د ویبپاڼې او اپلیکیشن جوړول",invoice:"حساب",bonus:"اونیز بونس",shipping:"۳۴ ولایتونو ته لېږد",admin:"د مدیریت پینل",welcome:"AZIMI SHOP ته ښه راغلاست",back:"← کور",view:"محصولات وګورئ →",add:"سبد ته اضافه",moved:"✓ حساب ته ولېږدول شو",empty:"تر اوسه دلته محصول نشته.",cartEmpty:"ستاسو سبد خالي دی.",total:"ټول",orderInfo:"د سپارښتنې معلومات",name:"بشپړ نوم",wa:"فعال WhatsApp شمېره",phone:"د تلیفون شمېره",province:"ولایت وټاکئ",address:"دقیق پته، ناحیه، کوڅه او د سپارلو ځای",order:"سپارښتنه ثبت او WhatsApp چمتو کړئ",homeTitle:"توپیر سره واخلئ،|توپیر سره تجربه کړئ.",homeDesc:"AZIMI SHOP د غوره محصولاتو، ځانګړو تخفیفونو، ډیجیټل خدمتونو او د افغانستان ټولو ۳۴ ولایتونو ته لېږد لپاره.",enter:"هټۍ ته ننوتل ↗",catHint:"یوه برخه وټاکئ؛ محصولات یوازې مدیریت زیاتوي.",discountEmpty:"تر اوسه تخفیفي محصول نشته.",servicesTitle:"AZIMI ډیجیټل خدمتونه",servicesDesc:"د ویبپاڼو، آنلاین هټیو، موبایل اپلیکیشنونو او کمپیوټري سافټویرونو جوړول.",web:"د ویبپاڼې ډیزاین",webDesc:"شرکتي، پلورنځي او ځانګړې ویبپاڼې",mobile:"موبایل اپلیکیشن",mobileDesc:"Android / iOS",desktop:"کمپیوټري سافټویر",desktopDesc:"ځانګړي سیستمونه",weekly:"هر مشتری په اوونۍ کې یو چانس لري.",spin:"څرخ وګرځوئ",shippingDesc:"ټولو ۳۴ ولایتونو ته د سپارښتنو لېږد شونی دی.",register:"نوی محصول ثبت کړئ",pname:"د محصول نوم",desc:"تشریح",price:"بیه",sale:"تخفیفي بیه (اختیاري)",stock:"موجودي",photo:"له موبایل یا کمپیوټر څخه د محصول عکس وټاکئ",category:"برخه",registerBtn:"محصول ثبت کړئ",prizeManage:"د بونس مدیریت",prizeName:"د جایزې نوم",addPrize:"جایزه اضافه کړئ",delete:"حذف",registered:"ثبت شوي محصولات",noProduct:"تر اوسه محصول نه دی ثبت شوی.",statsCat:"د هټۍ برخې",statsProv:"تر پوښښ لاندې ولایتونه",statsChance:"اونیز چانس",statsOnline:"آنلاین نندارتون",successCart:"محصول سبد ته اضافه شو 🛒",successOrder:"سپارښتنه WhatsApp ته چمتو شوه",fill:"د لېږد ټول معلومات بشپړ کړئ",emptyCart:"سبد خالي دی",registeredProduct:"محصول #",thisWeek:"تاسو د دې اوونۍ چانس کارولی دی.",prize:"🎉 ستاسو جایزه:",purpose:"Premium digital market",imgTip:"ټاکل شوی عکس"},
ar:{home:"الرئيسية",store:"المتجر",discounts:"العروض",services:"تصميم المواقع والتطبيقات",invoice:"الفاتورة",bonus:"المكافأة الأسبوعية",shipping:"التوصيل إلى 34 ولاية",admin:"لوحة الإدارة",welcome:"مرحباً بك في AZIMI SHOP",back:"← الرئيسية",view:"مشاهدة المنتجات ←",add:"أضف إلى السلة",moved:"✓ نُقل إلى الفاتورة",empty:"لا توجد منتجات هنا بعد.",cartEmpty:"سلة التسوق فارغة.",total:"المجموع",orderInfo:"معلومات الطلب",name:"الاسم الكامل",wa:"رقم WhatsApp فعال",phone:"رقم الهاتف",province:"اختر الولاية",address:"العنوان الدقيق، المنطقة والشارع ومكان التسليم",order:"تسجيل الطلب وتجهيز WhatsApp",homeTitle:"تسوق بشكل مختلف،|وعش تجربة مختلفة.",homeDesc:"AZIMI SHOP للمنتجات المختارة والعروض والخدمات الرقمية والتوصيل إلى جميع ولايات أفغانستان.",enter:"دخول المتجر ↗",catHint:"اختر فئة؛ المنتجات تُضاف من الإدارة فقط.",discountEmpty:"لا توجد منتجات مخفضة بعد.",servicesTitle:"خدمات AZIMI الرقمية",servicesDesc:"تصميم وتطوير المواقع والمتاجر الإلكترونية وتطبيقات الهاتف وبرامج الكمبيوتر.",web:"تصميم المواقع",webDesc:"مواقع شركات ومتاجر ومواقع مخصصة",mobile:"تطبيقات الهاتف",mobileDesc:"Android / iOS",desktop:"برامج الكمبيوتر",desktopDesc:"أنظمة مخصصة",weekly:"لكل عميل فرصة واحدة كل أسبوع.",spin:"أدر العجلة",shippingDesc:"التوصيل متاح إلى جميع الولايات الـ34.",register:"تسجيل منتج جديد",pname:"اسم المنتج",desc:"الوصف",price:"السعر",sale:"سعر التخفيض (اختياري)",stock:"المخزون",photo:"اختر صورة المنتج من الهاتف أو الكمبيوتر",category:"الفئة",registerBtn:"تسجيل المنتج",prizeManage:"إدارة جوائز المكافأة",prizeName:"اسم الجائزة",addPrize:"إضافة جائزة",delete:"حذف",registered:"المنتجات المسجلة",noProduct:"لا توجد منتجات مسجلة بعد.",statsCat:"فئات المتجر",statsProv:"الولايات المغطاة",statsChance:"الفرصة الأسبوعية",statsOnline:"المعرض الإلكتروني",successCart:"تمت إضافة المنتج إلى السلة 🛒",successOrder:"الطلب جاهز للإرسال عبر WhatsApp",fill:"أكمل معلومات التوصيل",emptyCart:"السلة فارغة",registeredProduct:"المنتج #",thisWeek:"لقد استخدمت فرصة هذا الأسبوع.",prize:"🎉 جائزتك:",purpose:"Premium digital market",imgTip:"الصورة المحددة"},
tr:{home:"Ana Sayfa",store:"Mağaza",discounts:"İndirimli Ürünler",services:"Web ve Uygulama Tasarımı",invoice:"Fatura",bonus:"Haftalık Bonus",shipping:"34 Vilayete Kargo",admin:"Yönetim Paneli",welcome:"AZIMI SHOP'a Hoş Geldiniz",back:"← Ana Sayfa",view:"Ürünleri Gör →",add:"Sepete Ekle",moved:"✓ Faturaya aktarıldı",empty:"Bu bölümde henüz ürün yok.",cartEmpty:"Sepetiniz boş.",total:"Toplam",orderInfo:"Sipariş bilgileri",name:"Ad Soyad",wa:"Aktif WhatsApp numarası",phone:"Telefon numarası",province:"İl seçin",address:"Tam adres, bölge, sokak ve teslimat yeri",order:"Sipariş ver ve WhatsApp'ı hazırla",homeTitle:"Farklı alışveriş,|farklı deneyim.",homeDesc:"AZIMI SHOP; seçilmiş ürünler, özel indirimler, dijital hizmetler ve Afganistan'ın 34 vilayetine teslimat.",enter:"Mağazaya Gir ↗",catHint:"Bir kategori seçin; ürünler yalnızca yönetim tarafından eklenir.",discountEmpty:"Henüz indirimli ürün yok.",servicesTitle:"AZIMI Dijital Hizmetler",servicesDesc:"Web sitesi, e-ticaret mağazası, mobil uygulama ve bilgisayar yazılımı geliştirme.",web:"Web Tasarımı",webDesc:"Kurumsal, mağaza ve özel siteler",mobile:"Mobil Uygulama",mobileDesc:"Android / iOS",desktop:"Bilgisayar Yazılımı",desktopDesc:"Özel sistemler",weekly:"Her müşterinin haftada bir şansı vardır.",spin:"Çarkı Çevir",shippingDesc:"34 Afganistan vilayetinin tamamına teslimat yapılır.",register:"Yeni Ürün Kaydet",pname:"Ürün adı",desc:"Açıklama",price:"Fiyat",sale:"İndirimli fiyat (isteğe bağlı)",stock:"Stok",photo:"Telefondan veya bilgisayardan ürün fotoğrafı seçin",category:"Kategori",registerBtn:"Ürünü Kaydet",prizeManage:"Bonus Yönetimi",prizeName:"Ödül adı",addPrize:"Ödül ekle",delete:"Sil",registered:"Kayıtlı ürünler",noProduct:"Henüz ürün kaydedilmedi.",statsCat:"Mağaza kategorileri",statsProv:"Hizmet verilen vilayetler",statsChance:"Haftalık şans",statsOnline:"Çevrimiçi vitrin",successCart:"Ürün sepete eklendi 🛒",successOrder:"Sipariş WhatsApp için hazır",fill:"Teslimat bilgilerini tamamlayın",emptyCart:"Sepet boş",registeredProduct:"Ürün #",thisWeek:"Bu haftaki hakkınızı zaten kullandınız.",prize:"🎉 Ödülünüz:",purpose:"Premium digital market",imgTip:"Seçilen fotoğraf"}
};
const BT={
 fa:{slots:"۷ جایزه بونوس",winner:"جایزه برنده این هفته",image:"عکس جایزه",save:"ذخیره تنظیمات بونوس",same:"نتیجه چرخ برای همه یکسان است",slot:"گزینه",empty:"خالی است"},
 en:{slots:"7 bonus prizes",winner:"This week’s winning prize",image:"Prize image",save:"Save bonus settings",same:"The wheel result is the same for everyone",slot:"Slot",empty:"Empty"},
 ps:{slots:"۷ د بونس جایزې",winner:"د دې اوونۍ ګټونکې جایزه",image:"د جایزې عکس",save:"د بونس تنظیمات خوندي کړئ",same:"د څرخ پایله د ټولو لپاره یوه ده",slot:"اختیار",empty:"خالي"},
 ar:{slots:"7 جوائز للمكافأة",winner:"الجائزة الفائزة هذا الأسبوع",image:"صورة الجائزة",save:"حفظ إعدادات المكافأة",same:"نتيجة العجلة متطابقة للجميع",slot:"الخيار",empty:"فارغ"},
 tr:{slots:"7 bonus ödülü",winner:"Bu haftanın kazanan ödülü",image:"Ödül görseli",save:"Bonus ayarlarını kaydet",same:"Çark sonucu herkes için aynıdır",slot:"Seçenek",empty:"Boş"}
};
function bt(k){return (BT[lang]&&BT[lang][k])||BT.fa[k]||k}
function getBonusConfig(){
 let raw=null;try{raw=JSON.parse(localStorage.getItem("azimi_bonus_config")||"null")}catch(e){}
 let slots=[];let winner=0;
 if(raw&&Array.isArray(raw.slots)){slots=raw.slots.map(x=>typeof x==="string"?{name:x,img:""}:{name:x?.name||"",img:x?.img||""})}
 else {
  try{const old=JSON.parse(localStorage.getItem("azimi_prizes")||"null");if(Array.isArray(old))slots=old.map(x=>typeof x==="string"?{name:x,img:""}:x)}catch(e){}
 }
 while(slots.length<7)slots.push({name:"",img:""});
 slots=slots.slice(0,7);
 if(raw&&Number.isInteger(raw.winner))winner=Math.max(0,Math.min(6,raw.winner));
 return {slots,winner};
}
function saveBonusConfig(cfg){localStorage.setItem("azimi_bonus_config",JSON.stringify(cfg));localStorage.setItem("azimi_prizes",JSON.stringify(cfg.slots.map(x=>x.name).filter(Boolean)))}
function bonusKey(){return new Date().getFullYear()+"-"+getWeek()}
function bonusWinner(){const cfg=getBonusConfig();let i=cfg.winner;if(!cfg.slots[i]?.name)i=cfg.slots.findIndex(x=>x.name);return i>=0?cfg.slots[i]:null}
function t(k){return (T[lang]&&T[lang][k])||T.fa[k]||k}
function save(){localStorage.setItem("azimi_products",JSON.stringify(products));localStorage.setItem("azimi_cart",JSON.stringify(cart));document.getElementById("cartCount").textContent=cart.reduce((a,x)=>a+x.qty,0)}
function toast(x){const e=document.getElementById("toast");e.textContent=x;e.className="toast";setTimeout(()=>e.className="",2500)}
function showPage(page){currentPage=page==="cart"?"invoice":page;document.querySelectorAll(".sidebar button").forEach(x=>x.classList.remove("active"));if(currentPage==="home")home();if(currentPage==="store")store();if(currentPage==="discounts")discounts();if(currentPage==="services")services();if(currentPage==="invoice")invoice();if(currentPage==="bonus")bonus();if(currentPage==="shipping")shipping();if(currentPage==="admin"){if(!isAdmin()){return;}admin();}const btn=[...document.querySelectorAll(".sidebar button")].find(x=>x.getAttribute("onclick")===`showPage('${currentPage}')`);if(btn)btn.classList.add("active");window.scrollTo({top:0,behavior:"smooth"})}
function shell(title,html){app.innerHTML=`<section class="page"><a href="#" onclick="showPage('home');return false" class="sub">${t("back")}</a><h1 class="page-title">${title}</h1>${html}</section>`}
function home(){app.innerHTML=`<section class="page hero"><div><div class="eyebrow">AZIMI / PREMIUM MARKET</div><h1>${t("homeTitle").replace("|","<br><em>")}${t("homeTitle").includes("|")?"</em>":""}</h1><p>${t("homeDesc")}</p><button class="primary" onclick="showPage('store')">${t("enter")}</button></div><div class="hero-art"><div class="ring a"></div><div class="ring b"></div><div class="core">AZ<br><small>SHOP</small></div></div></section><div class="stats"><div><b>07</b><small>${t("statsCat")}</small></div><div><b>34</b><small>${t("statsProv")}</small></div><div><b>01</b><small>${t("statsChance")}</small></div><div><b>24/7</b><small>${t("statsOnline")}</small></div></div>`}
function store(){shell("🛍️ "+t("store"),`<p class="sub">${t("catHint")}</p><div class="categories">${categories.map(c=>`<button class="cat" onclick="productsPage('${c[1]}')"><img class="cat-photo" src="${categoryImages[c[1]]}" alt="${catName(c[1])}" loading="lazy"><b>${catName(c[1])}</b><small>${t("view")}</small></button>`).join("")}</div>`)}
function catName(cat){const m={health:{fa:"فروشگاه بهداشتی",en:"Health Store",ps:"روغتیايي هټۍ",ar:"المتجر الصحي",tr:"Sağlık Mağazası"},clothes:{fa:"فروشگاه لباس",en:"Clothing Store",ps:"د جامو هټۍ",ar:"متجر الملابس",tr:"Giyim Mağazası"},electronics:{fa:"لوازم الکترونی",en:"Electronics",ps:"برقي وسایل",ar:"الإلكترونيات",tr:"Elektronik"},shoes:{fa:"کفش",en:"Shoes",ps:"بوټان",ar:"الأحذية",tr:"Ayakkabı"},watches:{fa:"ساعت های برند",en:"Branded Watches",ps:"برانډ ساعتونه",ar:"ساعات ماركات",tr:"Markalı Saatler"},computers:{fa:"کامپیوتر ها",en:"Computers",ps:"کمپیوټرونه",ar:"أجهزة الكمبيوتر",tr:"Bilgisayarlar"},phones:{fa:"گوشی ها",en:"Phones",ps:"موبایلونه",ar:"الهواتف",tr:"Telefonlar"}};return m[cat]?.[lang]||m[cat]?.fa||cat}
function productsPage(cat){let p=products.filter(x=>x.cat===cat);shell(catName(cat),`<div class="products">${p.map(card).join("")||`<div class="box"><p>${t("empty")}</p></div>`}</div>`)}
function card(p){let q=`qty_${p.id}`;return `<article class="product"><div class="pic">${p.img?`<img src="${p.img}" draggable="false">`:`<img src="${categoryImages[p.cat]||uiImages.store}" alt="${p.name}" draggable="false" loading="lazy">`}<label class="num">#${p.number}</label></div><div class="pbody"><small>${catName(p.cat)}</small><h3>${p.name}</h3><p>${p.desc||""}</p>${p.sale?`<del>${p.price} AFN</del><span class="price">${p.sale} AFN</span>`:`<span class="price">${p.price} AFN</span>`}<div class="product-actions"><div class="qty-control"><button type="button" onclick="changeQtyInput('${q}',-1)">−</button><span id="${q}">1</span><button type="button" onclick="changeQtyInput('${q}',1)">+</button></div><button class="add" onclick="addCart(${p.id},getQtyInput('${q}'))">${t("add")}</button></div><small class="add-note">${t("moved")}</small></div></article>`}
function getQtyInput(id){return Math.max(1,Number(document.getElementById(id)?.textContent||1))}
function changeQtyInput(id,delta){let e=document.getElementById(id);if(!e)return;e.textContent=Math.max(1,Number(e.textContent||1)+delta)}
function addCart(id,qty=1){let p=products.find(x=>x.id===id),old=cart.find(x=>x.id===id);if(!p)return;if(old)old.qty+=qty;else cart.push({...p,qty});save();toast(t("successCart"))}
function discounts(){let p=products.filter(x=>x.sale);shell(`<img class="title-photo" src="${uiImages.discounts}" alt="">`+t("discounts"),`<div class="products">${p.map(card).join("")||`<div class="box">${t("discountEmpty")}</div>`}</div>`)}
function services(){shell(`<img class="title-photo" src="${uiImages.services}" alt="">`+t("services"),`<div class="box"><h2>${t("servicesTitle")}</h2><p class="sub">${t("servicesDesc")}</p><div class="categories"><div class="cat"><img class="cat-photo" src="https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=700&q=85" alt="website"><b>${t("web")}</b><small>${t("webDesc")}</small></div><div class="cat"><img class="cat-photo" src="https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?auto=format&fit=crop&w=700&q=85" alt="mobile"><b>${t("mobile")}</b><small>${t("mobileDesc")}</small></div><div class="cat"><img class="cat-photo" src="https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=700&q=85" alt="computer"><b>${t("desktop")}</b><small>${t("desktopDesc")}</small></div></div></div>`)}
function invoice(){let total=cart.reduce((s,x)=>s+(Number(x.sale||x.price)*x.qty),0);shell(`<img class="title-photo" src="${uiImages.invoice}" alt="">`+t("invoice"),`<div class="box">${cart.length?cart.map(x=>`<div class="invoice-row"><span>${x.name} × ${x.qty}</span><div class="invoice-actions"><button onclick="changeCartQty(${x.id},-1)">−</button><b>${x.qty}</b><button onclick="changeCartQty(${x.id},1)">+</button><strong>${Number(x.sale||x.price)*x.qty} AFN</strong></div></div>`).join(""):`<p class="sub">${t("cartEmpty")}</p>`}<h2>${t("total")}: ${total} AFN</h2><div class="form"><h3>${t("orderInfo")}</h3><input id="cname" placeholder="${t("name")}"/><input id="wa" placeholder="${t("wa")}"/><input id="phone" placeholder="${t("phone")}"/><select id="province"><option value="">${t("province")}</option>${provinces.map(x=>`<option>${x}</option>`).join("")}</select><textarea id="address" placeholder="${t("address")}"></textarea><button class="primary" onclick="order()">${t("order")}</button></div></div>`)}
function changeCartQty(id,d){let x=cart.find(x=>x.id===id);if(!x)return;x.qty+=d;if(x.qty<=0)cart=cart.filter(y=>y.id!==id);save();invoice()}
function order(){if(!cart.length)return toast(t("emptyCart"));let name=document.getElementById("cname")?.value.trim(),wa=document.getElementById("wa")?.value.trim(),phone=document.getElementById("phone")?.value.trim(),prov=document.getElementById("province")?.value,addr=document.getElementById("address")?.value.trim();if(!name||!wa||!phone||!prov||!addr)return toast(t("fill"));let total=cart.reduce((s,x)=>s+(Number(x.sale||x.price)*x.qty),0);orderNo++;localStorage.setItem("azimi_order_no",orderNo);let lines=cart.map(x=>`#${x.number} ${x.name} x ${x.qty} = ${Number(x.sale||x.price)*x.qty} AFN`).join("\n");let msg=`AZIMI SHOP — Order ${orderNo}\n\n${lines}\n\n${t("total")}: ${total} AFN\n${t("name")}: ${name}\n${t("province")}: ${prov}\n${t("address")}: ${addr}\n${t("phone")}: ${phone}\n${t("wa")}: ${wa}`;localStorage.setItem("azimi_last_order",JSON.stringify({orderNo,cart,total,name,wa,phone,prov,addr,date:new Date().toISOString()}));const url="https://wa.me/"+WA+"?text="+encodeURIComponent(msg);window.open(url,"_blank","noopener,noreferrer");toast(t("successOrder"));setTimeout(()=>shareOrderFiles(msg),150)}
async function shareOrderFiles(msg){let files=[];for(const x of cart){if(x.img&&x.img.startsWith("data:")){try{let f=await dataURLtoFile(x.img,`AZIMI-${x.number}-${safeFileName(x.name)}.jpg`);if(f)files.push(f)}catch(e){}}}if(navigator.share&&files.length&&navigator.canShare&&navigator.canShare({files})){try{await navigator.share({title:"AZIMI SHOP",text:msg,files})}catch(e){}}}
function safeFileName(x){return String(x||"product").replace(/[^a-zA-Z0-9-_]/g,"-").slice(0,40)}
async function dataURLtoFile(dataurl,filename){let r=await fetch(dataurl);let b=await r.blob();return new File([b],filename,{type:b.type||"image/jpeg"})}
function bonus(){let cfg=getBonusConfig();let labels=cfg.slots.map((x,i)=>{let name=x.name||`${bt("slot")} ${i+1}`;let img=x.img?`<img src="${x.img}" alt="">`:"";let a=i*360/7;return `<div class="wheel-label" style="--a:${a}deg"><span>${img}<b>${escapeHtml(name)}</b></span></div>`}).join("");shell(`<img class="title-photo" src="${uiImages.bonus}" alt="">`+t("bonus"),`<div class="center"><p class="sub">${t("weekly")}</p><div class="wheel-wrap"><div class="wheel-pointer"></div><div class="wheel" id="wheel"><div class="wheel-labels">${labels}</div><div class="wheel-center">AZ</div></div></div><div class="bonus-wheel-items">${cfg.slots.map((x,i)=>`<div><b>${i+1}.</b> ${escapeHtml(x.name||bt("slot")+" "+(i+1))}</div>`).join("")}</div><button class="primary" onclick="spin()">${t("spin")}</button><div id="prize"></div></div>`)}
function spin(){let key=bonusKey();if(bonusWeek===key)return toast(t("thisWeek"));let cfg=getBonusConfig(),win=bonusWinner();if(!win?.name)return toast(bt("empty"));let idx=cfg.slots.findIndex(x=>x===win);let angle=1440-(idx<0?0:idx)*360/7;let wheel=document.getElementById("wheel");if(wheel)wheel.style.transform=`rotate(${angle}deg)`;setTimeout(()=>{document.getElementById("prize").innerHTML=`<div class="prize">${t("prize")} <b>${win.name}</b>${win.img?`<img class="prize-image" src="${win.img}" alt="">`:""}</div>`;bonusWeek=key;localStorage.setItem("azimi_bonus_week",key)},2000)}
function getWeek(){let d=new Date(),one=new Date(d.getFullYear(),0,1);return Math.ceil((((d-one)/86400000)+one.getDay()+1)/7)}
function shipping(){shell(`<img class="title-photo" src="https://upload.wikimedia.org/wikipedia/commons/0/09/Afghanistan_provinces_blue.png" alt="Afghanistan map" onerror="this.style.display='none'">`+t("shipping"),`<p class="sub">${t("shippingDesc")}</p><div class="afghanistan-map-card"><img src="https://upload.wikimedia.org/wikipedia/commons/0/09/Afghanistan_provinces_blue.png" alt="Afghanistan provinces map" onerror="this.onerror=null;this.src='https://commons.wikimedia.org/wiki/Special:Redirect/file/Afghanistan%20provinces%20blue.png'"></div><div class="province-grid">${provinces.map((x,i)=>`<div class="province"><span>${String(i+1).padStart(2,"0")}</span>${x}</div>`).join("")}</div>`)}
function isAdmin(){return sessionStorage.getItem("azimi_admin_auth")==="1"}
function adminLogin(){sessionStorage.setItem("azimi_admin_auth","1");showPage("admin")}
function adminLogout(){sessionStorage.removeItem("azimi_admin_auth");showPage("home")}
function admin(){let cfg=getBonusConfig();shell(`<img class="title-photo" src="${uiImages.store}" alt="">`+t("admin")+` <button class="danger" onclick="adminLogout()" style="float:left">خروج مدیریت</button>`,`<div class="admin-grid"><div class="box admin"><h3>${t("register")}</h3><input id="aname" placeholder="${t("pname")}"><input id="adesc" placeholder="${t("desc")}"><input id="aprice" type="number" placeholder="${t("price")}"><input id="asale" type="number" placeholder="${t("sale")}"><input id="astock" type="number" placeholder="${t("stock")}"><label class="admin-upload">${t("photo")}<input id="aimgFile" type="file" accept="image/*" onchange="previewProductImage(event)" style="margin-top:8px;width:100%"><img id="aimgPreview" class="admin-preview"></label><select id="acat">${categories.map(c=>`<option value="${c[1]}">${catName(c[1])}</option>`).join("")}</select><button class="primary" onclick="addProduct()">${t("registerBtn")}</button></div><div class="box admin bonus-admin"><h3>${t("prizeManage")}</h3><p class="sub">${bt("same")}</p><div class="bonus-winner"><label>${bt("winner")}</label><select id="bonusWinner">${cfg.slots.map((p,i)=>`<option value="${i}" ${cfg.winner===i?"selected":""}>${bt("slot")} ${i+1}${p.name?` — ${p.name}`:` — ${bt("empty")}`}</option>`).join("")}</select></div><div class="bonus-slots">${cfg.slots.map((p,i)=>`<div class="bonus-slot"><div class="bonus-slot-head"><b>${bt("slot")} ${i+1}</b></div><input id="bonusName_${i}" value="${escapeAttr(p.name)}" placeholder="${t("prizeName")}"><label class="admin-upload">${bt("image")}<input id="bonusImg_${i}" type="file" accept="image/*" onchange="previewBonusImage(event,${i})"><img id="bonusPreview_${i}" class="bonus-preview" src="${p.img||""}" style="${p.img?"display:block":"display:none"}"></label></div>`).join("")}</div><button class="primary" onclick="saveBonusSettings()">${bt("save")}</button></div></div><div class="box admin-list"><h3>${t("registered")}</h3>${products.length?products.map(p=>`<div class="admin-item"><span>#${p.number} — ${p.name}</span><button class="danger" onclick="deleteProduct(${p.id})">${t("delete")}</button></div>`).join(""):t("noProduct")}</div>`)}
function escapeHtml(x){return String(x||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")}
function escapeAttr(x){return String(x||"").replace(/&/g,"&amp;").replace(/"/g,"&quot;").replace(/</g,"&lt;").replace(/>/g,"&gt;")}
let pendingImage="";
function previewProductImage(e){let f=e.target.files?.[0];if(!f)return;let r=new FileReader();r.onload=()=>{pendingImage=r.result;let im=document.getElementById("aimgPreview");if(im){im.src=pendingImage;im.style.display="block"}};r.readAsDataURL(f)}
function addProduct(){let p={id:Date.now(),number:products.length?Math.max(...products.map(x=>x.number))+1:1,name:document.getElementById("aname").value.trim(),desc:document.getElementById("adesc").value.trim(),price:Number(document.getElementById("aprice").value),sale:Number(document.getElementById("asale").value)||null,stock:Number(document.getElementById("astock").value)||0,img:pendingImage,cat:document.getElementById("acat").value};if(!p.name||!p.price)return toast("نام و قیمت را وارد کن / Enter name and price");products.push(p);pendingImage="";save();toast(t("registeredProduct")+p.number);admin()}
function deleteProduct(id){products=products.filter(p=>p.id!==id);cart=cart.filter(x=>x.id!==id);save();admin()}
function previewBonusImage(e,i){let f=e.target.files?.[0];if(!f)return;compressImageFile(f,900,700,.72).then(data=>{let im=document.getElementById(`bonusPreview_${i}`);if(im){im.src=data;im.style.display="block";im.dataset.value=data}})}
function compressImageFile(file,maxW,maxH,quality){return new Promise(resolve=>{const r=new FileReader();r.onload=()=>{const img=new Image();img.onload=()=>{let w=img.naturalWidth,h=img.naturalHeight,scale=Math.min(1,maxW/w,maxH/h);w=Math.round(w*scale);h=Math.round(h*scale);const c=document.createElement("canvas");c.width=w;c.height=h;c.getContext("2d").drawImage(img,0,0,w,h);resolve(c.toDataURL("image/jpeg",quality))};img.src=r.result};r.readAsDataURL(file)})}
function saveBonusSettings(){let cfg=getBonusConfig();cfg.winner=Math.max(0,Math.min(6,Number(document.getElementById("bonusWinner")?.value||0)));cfg.slots=cfg.slots.map((p,i)=>{let name=document.getElementById(`bonusName_${i}`)?.value.trim()||"";let preview=document.getElementById(`bonusPreview_${i}`);let img=preview?.dataset?.value||p.img||"";return {name,img}});saveBonusConfig(cfg);toast(bt("save"));admin()}
function applyLanguage(){
 document.documentElement.lang=lang;document.documentElement.dir=(lang==="en"||lang==="tr")?"ltr":"rtl";
 const map={fa:"فارسی",en:"English",ps:"پښتو",ar:"العربية",tr:"Türkçe"};
 const side=document.querySelector(".sidebar");
 side.innerHTML=`<div class="side-label">AZIMI / MENU</div>
 <button onclick="showPage('home')"><img class="nav-photo" src="${uiImages.home}" alt=""><span>${t("home")}</span></button>
 <button onclick="showPage('store')"><img class="nav-photo" src="${uiImages.store}" alt=""><span>${t("store")}</span></button>
 <button onclick="showPage('discounts')"><img class="nav-photo" src="${uiImages.discounts}" alt=""><span>${t("discounts")}</span></button>
 <button onclick="showPage('services')"><img class="nav-photo" src="${uiImages.services}" alt=""><span>${t("services")}</span></button>
 <button onclick="showPage('invoice')"><img class="nav-photo" src="${uiImages.invoice}" alt=""><span>${t("invoice")}</span></button>
 <button onclick="showPage('bonus')"><img class="nav-photo" src="${uiImages.bonus}" alt=""><span>${t("bonus")}</span></button>
 <button onclick="showPage('shipping')"><img class="nav-photo" src="${uiImages.shipping}" alt=""><span>${t("shipping")}</span></button>
 <label class="language-side"><span>Language / ژبه</span><select id="languageSide">${Object.entries(map).map(([k,v])=>`<option value="${k}">${v}</option>`).join("")}</select></label>
 <div class="side-bottom">AZIMI SHOP<br><small>${t("purpose")}</small></div>`;
 const ls=document.getElementById("languageSide");ls.value=lang;ls.addEventListener("change",e=>{lang=e.target.value;localStorage.setItem("azimi_lang",lang);applyLanguage()});
 showPage(currentPage);
}

document.getElementById("themeBtn").onclick=()=>{document.body.classList.toggle("light");document.getElementById("themeBtn").textContent=document.body.classList.contains("light")?"🌙":"☀️";localStorage.setItem("azimi_theme",document.body.className)};
if(localStorage.getItem("azimi_theme")==="light")document.body.classList.add("light");
setTimeout(()=>document.getElementById("splash").classList.add("hide"),2300);save();applyLanguage();

document.addEventListener("contextmenu",e=>e.preventDefault());document.addEventListener("dragstart",e=>{if(e.target.tagName==="IMG")e.preventDefault()});
